/* Generated by scripts/aggregate.mjs — do not edit.
 * Ambient shapes for the generated child client imports: the built
 * ./client artifacts are loader factory files without type entry points,
 * so tsc must not resolve them; the bundle aliases these specifiers to
 * the child sources at build time (see the package tsdown.config.ts). */

declare module '@gestaltrun/dsh-client-ui-web-ui-settings/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-client-ui-plugin-manager/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-client-ui-market/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-client-ui-task-board/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-client-ui-git-graph/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-remote-web-ui/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-pet/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-ssh/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-tool-describe-image/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-liangshen/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-client-ui-skill-explorer/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-doctor/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-usage/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-session-archive/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-client-ui-model-capabilities/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-client-ui-preset-center/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}

declare module '@gestaltrun/dsh-client-ui-skin-center/client' {
  export const apply: unknown
  export const inject: readonly string[] | undefined
}
